### ISSUE TITLE
人工提供的验证集image.test.npz没有啊，只有image.npz还用不了

### ISSUE THREAD

**Issue by runsheng1** [zhaipro/easy12306#12]
把image.npz的数据代入到mlearn_for_image.py的人工提供的验证集部分，
在new_test_x[idx] = cv2.resize(test_x[idx], (67, 67))会报错
  File "mlearn_for_image.py", line 46, in load_data
    new_test_x[idx] = cv2.resize(t, (67, 67))
TypeError: src is not a numpy array, neither a scalar

**Comment by zhaipro** [comment]
我之前忘了将`captcha.test.npz`导入百度云。
可能还有忘记的，但谷歌云大概会齐全些吧，毕竟我主要在那里运行。
