### ISSUE TITLE
the model was *not* compiled. Compile it manually

### ISSUE THREAD

**Issue by wangsai0806** [zhaipro/easy12306#14]
E:\ProgramData\Anaconda3\lib\site-packages\keras\engine\saving.py:292: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '

运行mlearn.py的时候，出现这个错误，请问怎么解决，谢谢

**Comment by zhaipro** [comment]
不，这只是一个警告，其原因是我在保存模型时扔掉了优化器，为其减轻体重…

如果你只是用它，可以这样：
1. 人工忽略
1. 加个参数使加载时跳过编译

如果你还需要训练它：
1. 再编译它一下

**Comment by wangsai0806** [comment]
嗯嗯，感谢

**Comment by YoungXueya** [comment]
> 不，这只是一个警告，其原因是我在保存模型时扔掉了优化器，为其减轻体重…
> 
> 如果你只是用它，可以这样：
> 
> 1. 人工忽略
> 2. 加个参数使加载时跳过编译
> 
> 如果你还需要训练它：
> 
> 1. 再编译它一下

请问如何在加载时跳过编译呢？

**Comment by zhaipro** [comment]
> 请问如何在加载时跳过编译呢？

哇，我一个有强迫症的患者都选择忽略警告了，而你却…

```Python
In [47]: keras.models.load_model?
Signature: keras.models.load_model(filepath, custom_objects=None, compile=True)
```
