### ISSUE TITLE
深度学习需要哪些基础知识？

### ISSUE THREAD

**Issue by SJanJan** [zhaipro/easy12306#15]
Big-brother，can you tell me？please，thanks.
I  want to learn

**Comment by zhaipro** [comment]
我是看书自学的，http://www.ituring.com.cn/book/2599
基础知识是我从很多年前培养到现在的，所以我也没印象了。

**Comment by SJanJan** [comment]
> 我是看书自学的，http://www.ituring.com.cn/book/2599
> 基础知识是我从很多年前培养到现在的，所以我也没印象了。

Thanks,big brother
