### ISSUE TITLE
tensorflow版本

### ISSUE THREAD

**Issue by ghost** [zhaipro/easy12306#18]
请问您本项目的tensorflow版本是多少呀？

**Comment by zhaipro** [comment]
在线体验服务端用的是tensorflow==1.12.0
开发用的是谷歌云，不过最近找不到它了。

**Comment by ghost** [comment]
好的好的 谢谢您！
我刚刚用您训练好的模型参数测试了一下 发现文本和图片的预测准确率很低。8张子图好的情况下识别出一个子图，然后文字识别就基本挂掉。
请问您当时做的时候也是这么个情况么？
谢谢(^_^)




------------------ 原始邮件 ------------------
发件人: 宅教授 <notifications@github.com&gt;
发送时间: 2019年9月22日 12:18
收件人: zhaipro/easy12306 <easy12306@noreply.github.com&gt;
抄送: yuhaia <2802155264@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[zhaipro/easy12306] tensorflow版本 (#18)

**Comment by zhaipro** [comment]
之前的效果很好，在线体验的正确率应该能达到95%，不过那还是2.0.0版本。

**Comment by ghost** [comment]
shell.teachx.cn:12306/
测试效果也很差 没有您说的95%那么高，也是我之前说的那样 效果很差😢


------------------ 原始邮件 ------------------
发件人: 宅教授 <notifications@github.com&gt;
发送时间: 2019年9月22日 12:28
收件人: zhaipro/easy12306 <easy12306@noreply.github.com&gt;
抄送: yuhaia <2802155264@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[zhaipro/easy12306] tensorflow版本 (#18)




之前的效果很好，在线体验的正确率应该能达到95%，不过那还是2.0.0版本。

**Comment by zhaipro** [comment]
贴个样例给我看看吧，难道12306的验证码更新了？

**Comment by ghost** [comment]
您看一下，这几张图片都是选自您百度网盘分享的img文件夹下的图片。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"宅教授"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月22日(星期天) 中午12:35
收件人:&nbsp;"zhaipro/easy12306"<easy12306@noreply.github.com&gt;;
抄送:&nbsp;"海之蓝"<2802155264@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zhaipro/easy12306] tensorflow版本 (#18)




贴个样例给我看看吧，难道12306的验证码更新了？

**Comment by zhaipro** [comment]
饿，那是相当早起的验证码了，与现在的完全不同。你倒是可以用它再训练一波。

**Comment by ghost** [comment]
好的，我再看看。
谢谢您！

------------------ 原始邮件 ------------------
发件人: 宅教授 <notifications@github.com&gt;
发送时间: 2019年9月22日 12:45
收件人: zhaipro/easy12306 <easy12306@noreply.github.com&gt;
抄送: yuhaia <2802155264@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[zhaipro/easy12306] tensorflow版本 (#18)




饿，那是相当早起的验证码了，与现在的完全不同。你倒是可以用它再训练一波。
