### ISSUE TITLE
captcha.npz数据集生成问题

### ISSUE THREAD

**Issue by funnyyork** [zhaipro/easy12306#27]
请问captcha.npz怎么生成的，代码中没看到相关脚本？求解答~

**Comment by zhaipro** [comment]
代码超级杂乱，所以不知去向。

大体是对10万张验证码做了统计调查，比如某张图片一共出现了80次，其中有10次出现在了让找打字机的验证码中，所以呢，你觉得这张图是什么？

其中用到了文本识别和图片哈希。

**Comment by funnyyork** [comment]
![label](https://user-images.githubusercontent.com/40086850/79566998-04d32000-80e6-11ea-82c8-d5fcd0458e3d.png)
所以可以理解为每个图像的label为在不同类别下出现的次数，出现次数最多的，可以为认为它就是属于这个类别？

**Comment by zhaipro** [comment]
是的，统计方法可以参考：
https://github.com/zhaipro/easy12306/blob/master/category_images.py

**Comment by funnyyork** [comment]
好的，谢谢解答。
另外在文字分类中，我尝试通过将含有两个类别的图片分开，识别效果会有提升。
![fe7bb1fa-c121-4c39-bf5f-ac2f8d85bc17_](https://user-images.githubusercontent.com/40086850/79568745-fc301900-80e8-11ea-9db3-30177084145c.png)

**Comment by zhaipro** [comment]
具体的代码可以提交也让我看看。

**Comment by funnyyork** [comment]
没有什么特别的代码，就是对列求像素平均，就可以找出分割线，再对一些特殊情况，做一些处理。
