### ISSUE TITLE
文字识别在texts.npy的评价指标

### ISSUE THREAD

**Issue by neoql** [zhaipro/easy12306#28]
拜读了您的wiki，如果我没有理解错的话texts.npy中包含了百度识别不正确的验证码，也就是说这部分数据没有标注好的标准答案。
您在wiki中提到了，模型在这部分数据中取得了满意的结果。

我在复现您的代码，在这里有个疑问要请教下。您是如何在这部分没有标注答案的数据上评价模型的，是人工查看一些预测结果然后据此估计模型准确性？还是说有类似于训练时accuracy这样的可量化指标？

**Comment by zhaipro** [comment]
我有三个文件：`data.npy`、`texts.npz` 和 `texts.npy` （注意后缀…）

其中，data.npy是原始数据，texts.npz是从data.npy中根据百度识别制作出来的，而texts.npy是我在训练结束后又爬取了一批，用于玩耍的…

最后看一下我对百度识别的统计结果，是不是就明白啦：
https://gist.github.com/zhaipro/7cab2abc92dd2604d507437e64f07ff3
