### ISSUE TITLE
尝试了解各种相似图搜索算法

### ISSUE THREAD

**Issue by zhaipro** [zhaipro/easy12306#5]

**Comment by zhaipro** [comment]
根据[训练集](https://www.kaggle.com/libowei/12306-captcha-image)来验证各相似图搜索算法在此领域的能力。

1. `avhash` 错了8次，将整体压缩到6069个哈希值
1. `phash` ~ 0次，~ 6234个
1. `phash_simple` ~ n次，6533个。看来不能图简单呀
1. `dhash` ~ 0次，~ 7120个
1. `dhash_vertical` ~ 0次，~ 7244个

错的意思是指把两个不同类型的图片压缩到同一个哈希值。

**Comment by zhaipro** [comment]
尝试了解whash算法。

**Comment by xxllp** [comment]
cnn比这个还是靠谱点

**Comment by zhaipro** [comment]
> cnn比这个还是靠谱点

是的，这一步就是在为cnn准备训练集，其训练后的模型在各方面都表现良好，就是识别速度慢了点，不过这不重要。
