### ISSUE TITLE
建议弄个使用教程

### ISSUE THREAD

**Issue by 12374598858** [zhaipro/easy12306#7]
建议弄个使用教程。新手在运行的过程中，会出现很多莫名其妙的环境问题。

**Comment by zhaipro** [comment]
实际上，我的运行环境就是朝着混乱的方向行驶（无奈呀）。

不过，我还是会整理一下的（强迫症）。另外，请提出一些具体的莫名其妙的问题，也算是帮我了，对吧。

**Comment by 12374598858** [comment]
http://shell.teachx.cn:12306/  这个地址 为啥识别两个文字，只返回一个...

**Comment by 12374598858** [comment]
能加个QQ 交流下吗？ 1274598858、 问题随便填即可

**Comment by zhaipro** [comment]
> http://shell.teachx.cn:12306/ 这个地址 为啥识别两个文字，只返回一个...

[验证码有多个标签怎么训练？](https://github.com/zhaipro/easy12306/issues/3#issuecomment-454752845)

我个人搞这个项目只是处于兴趣。识别两个文字应该很容易（[尚未认证的思路](https://github.com/zhaipro/easy12306/wiki#%E5%B0%9A%E6%9C%AA%E8%AE%A4%E8%AF%81%E7%9A%84%E6%80%9D%E8%B7%AF)），但是没趣，但是一定有很有趣的方案，可是我的能力还达不到…

**Comment by hellozjf** [comment]
我把整个安装过程docker化了，可以将test.jpg放在/root/tmp目录下，然后使用`docker run --rm -v /root/tmp:/pic hellozjf/easy12306:1.0.0 test.jpg`查看运行结果

![](https://aliyun.hellozjf.com:7004/uploads/2019/3/20/menu.saveimg.savepath20190320133313.jpg)
