### ISSUE TITLE
我把main.py改造成了 api，结果至少需要2s才能返回。。

### ISSUE THREAD

**Issue by 12374598858** [zhaipro/easy12306#9]
http://shell.teachx.cn:12306/ 返回结果很快，你这服务器是啥配置的？
为啥我把main.py改造成了 api，结果至少需要2s才能返回。。

**Comment by zhaipro** [comment]
在线用的是v3.0.0版本的代码。

其中识图用的是哈希算法，它带来的识别力度已经足够了。坐等12306的验证码更新。
